import 'package:flutter/material.dart';

import '../core/formatting.dart';
import '../models/trip_models.dart';
import '../state/app_scope.dart';
import '../widgets/common.dart';

/// Port of `TripDetailActivity` / `activity_trip_detail.xml` — headline stats,
/// the verified eco-stay, the three-way transit comparison and the day-by-day
/// timeline.
class TripDetailScreen extends StatelessWidget {
  const TripDetailScreen({required this.trip, super.key});

  /// Passed as a route argument; falls back to the most recent saved trip, as
  /// the Activity did when launched without an extra.
  final TripPlan? trip;

  @override
  Widget build(BuildContext context) {
    final resolved = trip ?? AppScope.of(context).trips.getTrips().firstOrNull;
    if (resolved == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Trip')),
        body: const EmptyState(
          message: 'No trip to show yet — plan one with Yatri AI first.',
          icon: Icons.luggage_outlined,
        ),
      );
    }

    final theme = Theme.of(context);
    final transit = _transitOptions(resolved);

    return Scaffold(
      appBar: AppBar(title: const Text('Trip Itinerary')),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(16, 8, 16, 24),
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Text(
                  resolved.title,
                  style: theme.textTheme.headlineSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                '-${resolved.co2SavedKg} kg CO2',
                style: theme.textTheme.labelLarge?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Text(
            '${resolved.travelDates} • ${resolved.durationDays} Days Trip',
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            '🚆 ${resolved.travelMode} • ♿ '
            '${resolved.isStepFreeAccessible ? "100% Step-Free Concourse" : "Standard Concourse"}',
            style: theme.textTheme.bodySmall,
          ),
          if (!resolved.isAiGenerated) ...[
            const SizedBox(height: 8),
            Text(
              '⚠️ Offline template estimate — this plan was not generated by a live AI call.',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.error,
              ),
            ),
          ],
          const SizedBox(height: 16),
          SectionCard(
            child: Row(
              children: [
                Expanded(
                  child: StatTile(
                    label: 'TOTAL BUDGET',
                    value: rupees(resolved.totalBudgetInr),
                  ),
                ),
                Expanded(
                  child: StatTile(
                    label: 'AIR QUALITY',
                    value: resolved.aqiStatus,
                  ),
                ),
                Expanded(
                  child: StatTile(
                    label: 'REWARD POINTS',
                    value: '+${resolved.pulsePointsEarned}',
                    caption: 'PULSE',
                    valueColor: theme.colorScheme.primary,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          SectionCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Verified Eco-Stay',
                  style: theme.textTheme.titleSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                Text(resolved.hotelName, style: theme.textTheme.bodyMedium),
                Text(
                  '★ ${resolved.hotelRating} / 5.0',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: theme.colorScheme.primary,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Text(
            'Transit Comparison: Green Alternative vs Petrol Cab',
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          SectionCard(
            child: Column(
              children: [
                for (var i = 0; i < transit.length; i++) ...[
                  if (i > 0) const Divider(height: 20),
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          transit[i].$1,
                          style: theme.textTheme.bodyMedium,
                        ),
                      ),
                      Text(
                        transit[i].$2,
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.onSurfaceVariant,
                        ),
                      ),
                    ],
                  ),
                ],
              ],
            ),
          ),
          const SizedBox(height: 20),
          Text(
            'Day-by-Day Itinerary Schedule',
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          for (final day in resolved.dailyItinerary) ...[
            Padding(
              padding: const EdgeInsets.only(top: 16, bottom: 8),
              child: Text(
                'DAY ${day.dayNumber}: ${day.dayTitle}',
                style: theme.textTheme.titleSmall?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            for (final activity in day.activities) ...[
              _ActivityCard(activity: activity),
              const SizedBox(height: 10),
            ],
          ],
        ],
      ),
    );
  }

  /// Uses the plan's own transit options when the generator supplied them, and
  /// otherwise the destination-specific comparison the Activity fell back to.
  static List<(String, String)> _transitOptions(TripPlan trip) {
    if (trip.transitOpt1Name != null && trip.transitOpt1Name!.isNotEmpty) {
      return [
        (
          trip.transitOpt1Name!,
          trip.transitOpt1Metrics ?? 'Low Emission Transit',
        ),
        (
          trip.transitOpt2Name ?? '⚡ Alternative Transit Option',
          trip.transitOpt2Metrics ?? 'Eco Route',
        ),
        (
          trip.transitOpt3Name ?? '🚗 Private Standard Petrol Cab',
          trip.transitOpt3Metrics ?? 'High Carbon Footprint',
        ),
      ];
    }

    final dest = trip.destination.toLowerCase();
    if (dest.contains('matheran')) {
      return const [
        (
          '🚆 Central Railway Local + Toy Train',
          '₹110 • Level Boarding • 35g CO2',
        ),
        ('⚡ Neral E-Rickshaw + Shuttle', '₹90 • Zero Emission • 18g CO2'),
        (
          '🚗 Standard Petrol Taxi (to Dasturi)',
          '₹2,100 • 2h 30m • 1,600g CO2',
        ),
      ];
    }
    if (dest.contains('kedar')) {
      return const [
        (
          '🚆 Mumbai-Haridwar Superfast + E-Shuttle',
          '₹1,450 • Level Boarding • 280g CO2',
        ),
        ('⚡ AC Pilgrim Express Coach', '₹2,200 • AC Seater • 350g CO2'),
        (
          '🚗 Private Highway Diesel SUV Taxi',
          '₹18,500 • High Emissions • 24,000g CO2',
        ),
      ];
    }
    if (dest.contains('alibaug')) {
      return const [
        ('🚢 M2M Electric Hybrid Ro-Pax Ferry', '₹380 • 1h 15m • 45g CO2'),
        ('⚡ Mandwa Electric Feeder Bus', '₹40 • 20m • 10g CO2'),
        ('🚗 Standard Petrol Taxi (via Pen)', '₹2,800 • 3h 30m • 1,900g CO2'),
      ];
    }
    if (dest.contains('manali')) {
      return const [
        (
          '🚆 Vande Bharat + HRTC E-Coach',
          '₹1,850 • Electric Transit • 310g CO2',
        ),
        ('⚡ AC Electric Sleeper Coach', '₹2,400 • Overnight • 380g CO2'),
        (
          '🚗 Private Mountain Petrol Cab',
          '₹16,000 • Mountain Ghats • 22,000g CO2',
        ),
      ];
    }
    return const [
      ('🚆 Indrayani Electric Express', '₹75 • 2h 05m • 28g CO2'),
      ('⚡ MSRTC AC Shivneri E-Bus', '₹210 • 2h 20m • 54g CO2'),
      ('🚗 Standard Petrol Taxi', '₹3,200 • 2h 45m • 2,400g CO2'),
    ];
  }
}

class _ActivityCard extends StatelessWidget {
  const _ActivityCard({required this.activity});

  final TripActivity activity;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SectionCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                activity.time,
                style: theme.textTheme.labelMedium?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Text(
                  activity.title,
                  style: theme.textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            activity.description,
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: Text(
                  'Mode: ${activity.transportType} • '
                  '${activity.isAccessible ? "♿ Step-Free" : "Standard"} • '
                  '${activity.co2Grams}g CO2',
                  style: theme.textTheme.labelSmall?.copyWith(
                    color: theme.colorScheme.primary,
                  ),
                ),
              ),
              Text(
                activity.costInr > 0 ? rupees(activity.costInr) : 'Included',
                style: theme.textTheme.labelSmall?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
