import 'package:flutter/material.dart';

import '../core/formatting.dart';
import '../domain/carbon_estimator.dart';
import '../models/mobility.dart';
import '../models/trip_models.dart';
import '../state/app_scope.dart';
import '../widgets/common.dart';

/// Port of `TripDetailActivity` / `activity_trip_detail.xml` — headline stats,
/// the verified eco-stay, the three-way transit comparison and the day-by-day
/// timeline.
class TripDetailScreen extends StatelessWidget {
  const TripDetailScreen({required this.trip, super.key});

  /// Passed as a route argument; falls back to the most recent saved trip, as
  /// the Activity did when launched without an extra.
  final TripPlan? trip;

  @override
  Widget build(BuildContext context) {
    final resolved = trip ?? AppScope.of(context).trips.getTrips().firstOrNull;
    if (resolved == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Trip')),
        body: const EmptyState(
          message: 'No trip to show yet — plan one with Yatri AI first.',
          icon: Icons.luggage_outlined,
        ),
      );
    }

    final theme = Theme.of(context);
    final transit = _transitOptions(resolved);

    return Scaffold(
      appBar: AppBar(title: const Text('Trip Itinerary')),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(16, 8, 16, 24),
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Text(
                  resolved.title,
                  style: theme.textTheme.headlineSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                '-${resolved.co2SavedKg} kg CO2',
                style: theme.textTheme.labelLarge?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Text(
            '${resolved.travelDates} • ${resolved.durationDays} Days Trip',
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 6),
          Row(
            children: [
              Icon(Icons.directions_subway_outlined, size: 16, color: theme.colorScheme.onSurfaceVariant),
              const SizedBox(width: 4),
              Text(
                resolved.travelMode,
                style: theme.textTheme.bodySmall,
              ),
              const SizedBox(width: 12),
              Icon(Icons.accessible_outlined, size: 16, color: theme.colorScheme.onSurfaceVariant),
              const SizedBox(width: 4),
              Text(
                resolved.isStepFreeAccessible ? '100% Step-Free Concourse' : 'Standard Concourse',
                style: theme.textTheme.bodySmall,
              ),
            ],
          ),
          if (!resolved.isAiGenerated) ...[
            const SizedBox(height: 8),
            Row(
              children: [
                Icon(Icons.info_outline, size: 16, color: theme.colorScheme.error),
                const SizedBox(width: 6),
                Expanded(
                  child: Text(
                    'Offline template estimate — this plan was not generated by a live AI call.',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.error,
                    ),
                  ),
                ),
              ],
            ),
          ],
          const SizedBox(height: 16),
          SectionCard(
            child: Row(
              children: [
                Expanded(
                  child: StatTile(
                    label: 'TOTAL BUDGET',
                    value: rupees(resolved.totalBudgetInr),
                  ),
                ),
                Expanded(
                  child: StatTile(
                    label: 'AIR QUALITY',
                    value: resolved.aqiStatus,
                  ),
                ),
                Expanded(
                  child: StatTile(
                    label: 'REWARD POINTS',
                    value: '+${resolved.pulsePointsEarned}',
                    caption: 'PULSE',
                    valueColor: theme.colorScheme.primary,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          SectionCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Verified Eco-Stay',
                  style: theme.textTheme.titleSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                Text(resolved.hotelName, style: theme.textTheme.bodyMedium),
                Row(
                  children: [
                    Icon(Icons.star_rounded, size: 16, color: theme.colorScheme.primary),
                    const SizedBox(width: 4),
                    Text(
                      '${resolved.hotelRating} / 5.0',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.primary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Text(
            'Transit Comparison: Green Alternative vs Petrol Cab',
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          SectionCard(
            child: Column(
              children: [
                for (var i = 0; i < transit.length; i++) ...[
                  if (i > 0) const Divider(height: 20),
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(
                          color: theme.colorScheme.surfaceContainerHighest,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Icon(
                          transit[i].$1.toLowerCase().contains('bus')
                              ? Icons.directions_bus_outlined
                              : transit[i].$1.toLowerCase().contains('taxi') || transit[i].$1.toLowerCase().contains('cab')
                              ? Icons.directions_car_outlined
                              : Icons.directions_subway_outlined,
                          size: 16,
                          color: theme.colorScheme.primary,
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          transit[i].$1,
                          style: theme.textTheme.bodyMedium?.copyWith(
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Text(
                        transit[i].$2,
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.onSurfaceVariant,
                        ),
                      ),
                    ],
                  ),
                ],
              ],
            ),
          ),
          const SizedBox(height: 20),
          Text(
            'Day-by-Day Itinerary Schedule',
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          for (final day in resolved.dailyItinerary) ...[
            Padding(
              padding: const EdgeInsets.only(top: 16, bottom: 8),
              child: Text(
                'DAY ${day.dayNumber}: ${day.dayTitle}',
                style: theme.textTheme.titleSmall?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            for (final activity in day.activities) ...[
              _ActivityCard(activity: activity),
              const SizedBox(height: 10),
            ],
          ],
        ],
      ),
    );
  }

  /// Uses the plan's own transit options when the planner supplied them, and
  /// otherwise computes the comparison from the real distance between origin and
  /// destination — the same estimator the Green Route Planner uses. The Kotlin
  /// Activity carried four hand-written per-destination tables here.
  static List<(String, String)> _transitOptions(TripPlan trip) {
    if (trip.transitOpt1Name != null && trip.transitOpt1Name!.isNotEmpty) {
      return [
        (
          trip.transitOpt1Name!,
          trip.transitOpt1Metrics ?? 'Low Emission Transit',
        ),
        (
          trip.transitOpt2Name ?? 'Alternative transit option',
          trip.transitOpt2Metrics ?? 'Eco route',
        ),
        (
          trip.transitOpt3Name ?? 'Private standard petrol cab',
          trip.transitOpt3Metrics ?? 'High carbon footprint',
        ),
      ];
    }

    // Older saved trips predate the planner emitting transit options; derive the
    // comparison instead of inventing one.
    final distanceKm = CarbonEstimator.estimateDistanceKm(
      trip.travelMode,
      trip.destination,
    );
    final options = CarbonEstimator.estimateAllModes(distanceKm);
    String metrics(TravelMode mode) {
      final option = options.firstWhere((o) => o.mode == mode);
      return '${rupees(option.fareRupees)} • ${option.durationMin} mins • '
          '${fixed(option.carbonGrams, 0)}g CO2';
    }

    return [
      (TravelMode.metro.label, metrics(TravelMode.metro)),
      (TravelMode.bus.label, metrics(TravelMode.bus)),
      (TravelMode.taxi.label, metrics(TravelMode.taxi)),
    ];
  }
}

class _ActivityCard extends StatelessWidget {
  const _ActivityCard({required this.activity});

  final TripActivity activity;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SectionCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                activity.time,
                style: theme.textTheme.labelMedium?.copyWith(
                  color: theme.colorScheme.primary,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Text(
                  activity.title,
                  style: theme.textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            activity.description,
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: Text(
                  'Mode: ${activity.transportType} • '
                  '${activity.isAccessible ? "Step-Free" : "Standard"} • '
                  '${activity.co2Grams}g CO2',
                  style: theme.textTheme.labelSmall?.copyWith(
                    color: theme.colorScheme.primary,
                  ),
                ),
              ),
              Text(
                activity.costInr > 0 ? rupees(activity.costInr) : 'Included',
                style: theme.textTheme.labelSmall?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
