import 'package:latlong2/latlong.dart';

import '../agents/bhatkanti/hotspot_candidate.dart';
import '../models/itinerary/itinerary_parts.dart';

class CuratedSpot {
  const CuratedSpot({
    required this.name,
    required this.kind,
    required this.why,
    required this.dLat,
    required this.dLon,
    this.visitMinutes = 90,
    this.feeInr = 0,
    this.isOutdoor = true,
    this.isTrending = false,
    this.openingHours,
    this.wikiTitle,
  });

  final String name;
  final HotspotKind kind;
  final String why;
  final double dLat;
  final double dLon;
  final int visitMinutes;
  final int feeInr;
  final bool isOutdoor;
  final bool isTrending;
  final String? openingHours;
  final String? wikiTitle;
}

abstract final class CuratedDestinations {
  static const Map<String, List<CuratedSpot>> _db = {
    'munnar': [
      CuratedSpot(
        name: 'Eravikulam National Park (Rajamalai)',
        kind: HotspotKind.nature,
        why: 'Home to the endangered Nilgiri Tahr and rolling green shola grasslands.',
        dLat: 0.082,
        dLon: -0.045,
        visitMinutes: 150,
        feeInr: 200,
        isOutdoor: true,
        openingHours: 'Mo-Su 07:30-16:00',
        wikiTitle: 'Eravikulam National Park',
      ),
      CuratedSpot(
        name: 'KDHP Tea Museum & Factory',
        kind: HotspotKind.culture,
        why: 'Experience century-old tea manufacturing, CTC processing, and tea tasting.',
        dLat: -0.012,
        dLon: -0.018,
        visitMinutes: 90,
        feeInr: 125,
        isOutdoor: false,
        openingHours: 'Tu-Su 09:00-17:00; Mo off',
        wikiTitle: 'Munnar Tea Museum',
      ),
      CuratedSpot(
        name: 'Mattupetty Dam & Lake',
        kind: HotspotKind.viewpoint,
        why: 'Scenic masonry dam surrounded by tea hills, with speedboating and elephant sightings.',
        dLat: 0.015,
        dLon: 0.065,
        visitMinutes: 90,
        feeInr: 50,
        isOutdoor: true,
        openingHours: 'Mo-Su 09:30-17:00',
        wikiTitle: 'Mattupetty Dam',
      ),
      CuratedSpot(
        name: 'Echo Point Munnar',
        kind: HotspotKind.viewpoint,
        why: 'Natural acoustic echo phenomenon at the misty confluence of three mountain streams.',
        dLat: 0.042,
        dLon: 0.098,
        visitMinutes: 60,
        feeInr: 30,
        isOutdoor: true,
        openingHours: 'Mo-Su 06:00-18:00',
      ),
      CuratedSpot(
        name: 'Top Station Viewpoint',
        kind: HotspotKind.viewpoint,
        why: 'Highest point in Munnar offering breathtaking panoramic views of the Western Ghats.',
        dLat: 0.125,
        dLon: 0.185,
        visitMinutes: 120,
        feeInr: 50,
        isOutdoor: true,
        openingHours: 'Mo-Su 06:00-19:00',
        wikiTitle: 'Top Station',
      ),
      CuratedSpot(
        name: 'Attukad Waterfalls',
        kind: HotspotKind.nature,
        why: 'Cascading jungle waterfall amidst dense tea gardens and hanging wooden bridge.',
        dLat: -0.048,
        dLon: -0.035,
        visitMinutes: 75,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Kundala Dam & Cherry Blossom Lake',
        kind: HotspotKind.nature,
        why: 'Asia’s first arch dam with pedal boats and seasonal Neela Kurinji blossoms.',
        dLat: 0.075,
        dLon: 0.142,
        visitMinutes: 90,
        feeInr: 50,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Pothamedu Viewpoint',
        kind: HotspotKind.viewpoint,
        why: 'Sunset viewpoint overlooking emerald tea, coffee, and cardamom plantations.',
        dLat: -0.028,
        dLon: -0.022,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Blossom International Hydel Park',
        kind: HotspotKind.nature,
        why: 'Landscaped floral gardens with birdwatching trails, roller skating, and cycling.',
        dLat: -0.015,
        dLon: -0.008,
        visitMinutes: 75,
        feeInr: 40,
        isOutdoor: true,
        openingHours: 'Mo-Su 09:00-19:00',
      ),
      CuratedSpot(
        name: 'Rapsy Restaurant & Local Spice Market',
        kind: HotspotKind.food,
        why: 'Famous local hub for authentic Kerala parotta, beef fry, biryani, and cardamom.',
        dLat: 0.002,
        dLon: 0.003,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: false,
      ),
      CuratedSpot(
        name: 'Chinnar Wildlife Sanctuary',
        kind: HotspotKind.adventure,
        why: 'Dry deciduous sanctuary famous for the grizzled giant squirrel and watchtower treks.',
        dLat: 0.245,
        dLon: 0.125,
        visitMinutes: 180,
        feeInr: 150,
        isOutdoor: true,
        isTrending: true,
      ),
      CuratedSpot(
        name: 'Kolukkumalai Tea Estate',
        kind: HotspotKind.adventure,
        why: 'Highest organic tea plantation in the world reached via an exhilarating 4x4 jeep safari.',
        dLat: 0.095,
        dLon: 0.210,
        visitMinutes: 180,
        feeInr: 250,
        isOutdoor: true,
        isTrending: true,
      ),
    ],
    'jaipur': [
      CuratedSpot(
        name: 'Amber Palace (Amer Fort)',
        kind: HotspotKind.heritage,
        why: 'Grand 16th-century red sandstone fortress overlooking Maota Lake with Sheesh Mahal.',
        dLat: 0.088,
        dLon: 0.038,
        visitMinutes: 150,
        feeInr: 100,
        isOutdoor: true,
        openingHours: 'Mo-Su 08:00-17:30',
        wikiTitle: 'Amer Fort',
      ),
      CuratedSpot(
        name: 'Hawa Mahal (Palace of Winds)',
        kind: HotspotKind.heritage,
        why: 'Iconic five-storey pink facade with 953 honeycomb windows designed for royal women.',
        dLat: 0.012,
        dLon: 0.022,
        visitMinutes: 60,
        feeInr: 50,
        isOutdoor: false,
        openingHours: 'Mo-Su 09:00-17:00',
        wikiTitle: 'Hawa Mahal',
      ),
      CuratedSpot(
        name: 'City Palace Jaipur',
        kind: HotspotKind.heritage,
        why: 'Royal residence blending Mughal and Rajput architecture, Chandra Mahal, and Mubarak Mahal.',
        dLat: 0.015,
        dLon: 0.018,
        visitMinutes: 120,
        feeInr: 300,
        isOutdoor: true,
        openingHours: 'Mo-Su 09:30-17:00',
        wikiTitle: 'City Palace, Jaipur',
      ),
      CuratedSpot(
        name: 'Jantar Mantar',
        kind: HotspotKind.heritage,
        why: 'UNESCO World Heritage 18th-century astronomical observatory with world’s largest stone sundial.',
        dLat: 0.014,
        dLon: 0.019,
        visitMinutes: 75,
        feeInr: 50,
        isOutdoor: true,
        openingHours: 'Mo-Su 09:00-17:00',
        wikiTitle: 'Jantar Mantar, Jaipur',
      ),
      CuratedSpot(
        name: 'Nahargarh Fort & Sunset Point',
        kind: HotspotKind.viewpoint,
        why: 'Hilltop ramparts with striking sunset vistas across the entirety of the Pink City.',
        dLat: 0.045,
        dLon: 0.005,
        visitMinutes: 120,
        feeInr: 50,
        isOutdoor: true,
        wikiTitle: 'Nahargarh Fort',
      ),
      CuratedSpot(
        name: 'Jal Mahal (Water Palace)',
        kind: HotspotKind.viewpoint,
        why: 'Serene palace appearing to float in the middle of Man Sagar Lake.',
        dLat: 0.048,
        dLon: 0.032,
        visitMinutes: 45,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Jal Mahal',
      ),
      CuratedSpot(
        name: 'Albert Hall Museum',
        kind: HotspotKind.culture,
        why: 'Oldest state museum of Rajasthan exhibiting royal carpets, ivory, and metal sculptures.',
        dLat: -0.018,
        dLon: 0.016,
        visitMinutes: 90,
        feeInr: 40,
        isOutdoor: false,
        openingHours: 'Mo-Su 09:00-17:00',
        wikiTitle: 'Albert Hall Museum',
      ),
      CuratedSpot(
        name: 'Laxmi Mishthan Bhandar (LMB) Johari Bazaar',
        kind: HotspotKind.food,
        why: 'Historic culinary gem famous for hot pyaaz kachori, mawa kachori, and Rajasthani thali.',
        dLat: 0.010,
        dLon: 0.021,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: false,
      ),
    ],
    'goa': [
      CuratedSpot(
        name: 'Fort Aguada & Lighthouse',
        kind: HotspotKind.heritage,
        why: '17th-century Portuguese fortress overlooking the Sinquerim coast and Arabian Sea.',
        dLat: 0.045,
        dLon: -0.065,
        visitMinutes: 90,
        feeInr: 50,
        isOutdoor: true,
        wikiTitle: 'Fort Aguada',
      ),
      CuratedSpot(
        name: 'Basilica of Bom Jesus',
        kind: HotspotKind.heritage,
        why: 'UNESCO World Heritage baroque church containing the sacred mortal remains of St. Francis Xavier.',
        dLat: 0.052,
        dLon: 0.085,
        visitMinutes: 75,
        feeInr: 0,
        isOutdoor: false,
        wikiTitle: 'Basilica of Bom Jesus',
      ),
      CuratedSpot(
        name: 'Dudhsagar Waterfalls',
        kind: HotspotKind.nature,
        why: 'Spectacular 310-metre 4-tiered waterfall cascading like a sea of milk through Bhagwan Mahavir Sanctuary.',
        dLat: -0.150,
        dLon: 0.320,
        visitMinutes: 240,
        feeInr: 100,
        isOutdoor: true,
        isTrending: true,
        wikiTitle: 'Dudhsagar Falls',
      ),
      CuratedSpot(
        name: 'Chapora Fort (Dil Chahta Hai Point)',
        kind: HotspotKind.viewpoint,
        why: 'Red laterite cliff-top fort offering dramatic coastal vistas of Vagator Beach.',
        dLat: 0.125,
        dLon: -0.082,
        visitMinutes: 75,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Chapora Fort',
      ),
      CuratedSpot(
        name: 'Fontainhas Latin Quarter',
        kind: HotspotKind.culture,
        why: 'Charming historic quarter with pastel-coloured Portuguese colonial villas and art galleries.',
        dLat: 0.048,
        dLon: 0.038,
        visitMinutes: 90,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Fontainhas',
      ),
      CuratedSpot(
        name: 'Baga Beach & Water Sports Point',
        kind: HotspotKind.adventure,
        why: 'Vibrant beach famous for parasailing, jet skiing, banana boat rides, and lively beach shacks.',
        dLat: 0.082,
        dLon: -0.075,
        visitMinutes: 120,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Fisherman’s Wharf',
        kind: HotspotKind.food,
        why: 'Riverside dining famous for Goan fish curry, prawn balchão, and fresh crab recheado.',
        dLat: -0.050,
        dLon: 0.020,
        visitMinutes: 75,
        feeInr: 0,
        isOutdoor: false,
      ),
    ],
    'manali': [
      CuratedSpot(
        name: 'Solang Valley Adventure Hub',
        kind: HotspotKind.adventure,
        why: 'Snow adventure paradise for paragliding, zorbing, quad biking, and winter skiing.',
        dLat: 0.085,
        dLon: -0.045,
        visitMinutes: 180,
        feeInr: 100,
        isOutdoor: true,
        wikiTitle: 'Solang Valley',
      ),
      CuratedSpot(
        name: 'Hadimba Devi Temple',
        kind: HotspotKind.religious,
        why: 'Unique 4-tier wooden pagoda temple constructed in 1553 amidst towering deodar forests.',
        dLat: 0.012,
        dLon: -0.015,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Hidimba Devi Temple',
      ),
      CuratedSpot(
        name: 'Jogini Waterfall Trek',
        kind: HotspotKind.nature,
        why: 'Refreshing scenic stream trek through apple orchards and pine woods leading to cascading falls.',
        dLat: 0.035,
        dLon: 0.012,
        visitMinutes: 120,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Old Manali Cafe Trail & Market',
        kind: HotspotKind.culture,
        why: 'Bohemian alleyways lined with live music cafes, Tibetan handicraft stalls, and bakeries.',
        dLat: 0.018,
        dLon: -0.010,
        visitMinutes: 90,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Vashisht Hot Water Springs & Temple',
        kind: HotspotKind.nature,
        why: 'Natural therapeutic sulfur thermal springs and ancient stone temple overlooking Beas river.',
        dLat: 0.028,
        dLon: 0.015,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Atal Tunnel & Sissu Lahaul Valley',
        kind: HotspotKind.viewpoint,
        why: 'Engineering marvel through Pir Panjal mountains opening into majestic high-altitude waterfalls.',
        dLat: 0.220,
        dLon: -0.025,
        visitMinutes: 240,
        feeInr: 0,
        isOutdoor: true,
        isTrending: true,
      ),
    ],
    'panvel': [
      CuratedSpot(
        name: 'Karnala Bird Sanctuary',
        kind: HotspotKind.nature,
        why: 'Biodiverse sanctuary home to over 222 bird species and lush Western Ghats flora.',
        dLat: -0.085,
        dLon: 0.025,
        visitMinutes: 150,
        feeInr: 50,
        isOutdoor: true,
        wikiTitle: 'Karnala Bird Sanctuary',
      ),
      CuratedSpot(
        name: 'Karnala Fort (Funnel Hill)',
        kind: HotspotKind.heritage,
        why: 'Historic hill fort featuring a 125-foot basalt thumb-like pillar and panoramic views.',
        dLat: -0.088,
        dLon: 0.028,
        visitMinutes: 180,
        feeInr: 50,
        isOutdoor: true,
        wikiTitle: 'Karnala Fort',
      ),
      CuratedSpot(
        name: 'Gadeshwar Dam & Reservoir',
        kind: HotspotKind.nature,
        why: 'Peaceful reservoir surrounded by emerald hills, perfect for morning birdwatching and walks.',
        dLat: 0.045,
        dLon: 0.065,
        visitMinutes: 90,
        feeInr: 0,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Prabalgad & Kalavantin Durg Viewpoint',
        kind: HotspotKind.adventure,
        why: 'Renowned steep rock-cut steps leading to breathtaking views of Matheran plateau.',
        dLat: 0.065,
        dLon: 0.082,
        visitMinutes: 240,
        feeInr: 50,
        isOutdoor: true,
      ),
    ],
    'rishikesh': [
      CuratedSpot(
        name: 'The Beatles Ashram (Chaurasi Kutia)',
        kind: HotspotKind.heritage,
        why: 'Iconic forested sanctuary where The Beatles studied transcendental meditation in 1968, adorned with vibrant murals and stone dome huts.',
        dLat: -0.015,
        dLon: 0.025,
        visitMinutes: 120,
        feeInr: 150,
        isOutdoor: true,
        openingHours: 'Mo-Su 09:00-16:00',
        wikiTitle: 'Beatles Ashram',
      ),
      CuratedSpot(
        name: 'Triveni Ghat & Evening Ganga Aarti',
        kind: HotspotKind.religious,
        why: 'Sacred tri-river confluence where the daily Maha Aarti illuminates the Ganges with floating diya lamps, bells, and Vedic chants.',
        dLat: -0.045,
        dLon: -0.012,
        visitMinutes: 90,
        feeInr: 0,
        isOutdoor: true,
        openingHours: 'Mo-Su 06:00-21:00',
        wikiTitle: 'Triveni Ghat',
      ),
      CuratedSpot(
        name: 'Lakshman Jhula & Viewpoint',
        kind: HotspotKind.viewpoint,
        why: 'Historic 450-foot iron suspension bridge with sweeping views of the turquoise Ganges and Himalayan foothills.',
        dLat: 0.028,
        dLon: 0.038,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Lakshman Jhula',
      ),
      CuratedSpot(
        name: 'Ram Jhula & Swarg Ashram',
        kind: HotspotKind.culture,
        why: 'Scenic pedestrian bridge connecting serene spiritual ashrams, yoga retreats, and riverside souvenir lanes.',
        dLat: 0.012,
        dLon: 0.028,
        visitMinutes: 75,
        feeInr: 0,
        isOutdoor: true,
        wikiTitle: 'Ram Jhula',
      ),
      CuratedSpot(
        name: 'Neer Garh Waterfall',
        kind: HotspotKind.nature,
        why: 'Two-tier jade water cascade tucked away in lush forest canopies, perfect for refreshing natural dip pools.',
        dLat: 0.055,
        dLon: 0.042,
        visitMinutes: 120,
        feeInr: 50,
        isOutdoor: true,
      ),
      CuratedSpot(
        name: 'Parmarth Niketan Ashram',
        kind: HotspotKind.culture,
        why: 'Sprawling peaceful spiritual haven on the banks of Ganga featuring floral courtyards and world-famous evening prayers.',
        dLat: 0.008,
        dLon: 0.032,
        visitMinutes: 90,
        feeInr: 0,
        isOutdoor: true,
        openingHours: 'Mo-Su 07:00-20:00',
        wikiTitle: 'Parmarth Niketan',
      ),
      CuratedSpot(
        name: 'Tera Manzil Temple (Trimbakeshwar)',
        kind: HotspotKind.religious,
        why: '13-storey multi-tiered temple right beside the river offering panoramic rooftop perspectives of the holy valley.',
        dLat: 0.029,
        dLon: 0.039,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: false,
        openingHours: 'Mo-Su 06:00-19:00',
      ),
      CuratedSpot(
        name: 'Shivpuri River Rafting & Beach Point',
        kind: HotspotKind.adventure,
        why: 'Premier white-water rafting departure with Grade III/IV rapids, bodysurfing stretches, and white sand river beaches.',
        dLat: 0.120,
        dLon: 0.095,
        visitMinutes: 180,
        feeInr: 800,
        isOutdoor: true,
        isTrending: true,
      ),
      CuratedSpot(
        name: 'Little Buddha Cafe & River Overlook',
        kind: HotspotKind.food,
        why: 'Legendary treehouse cafe overlooking the Ganga serving organic smoothies, wood-fired thin crust pizzas, and Tibetan momos.',
        dLat: 0.026,
        dLon: 0.036,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: false,
        isTrending: true,
      ),
      CuratedSpot(
        name: 'Chotiwala Restaurant (Swargashram)',
        kind: HotspotKind.food,
        why: 'Heritage eatery operating since 1958 famous for authentic Garhwali thali, dal makhani, and hot jalebis.',
        dLat: 0.010,
        dLon: 0.030,
        visitMinutes: 60,
        feeInr: 0,
        isOutdoor: false,
      ),
    ],
  };

  /// Returns curated spots for [destination] if known, or empty list.
  static List<HotspotCandidate> getCurated(String destination, LatLng center) {
    final key = destination.trim().toLowerCase();
    String? matchedKey;
    for (final k in _db.keys) {
      if (key.contains(k) || k.contains(key)) {
        matchedKey = k;
        break;
      }
    }
    if (matchedKey == null) return const [];
    final spots = _db[matchedKey]!;
    return [
      for (final s in spots)
        HotspotCandidate(
          name: s.name,
          location: LatLng(
            (center.latitude + s.dLat).clamp(-90.0, 90.0),
            (center.longitude + s.dLon).clamp(-180.0, 180.0),
          ),
          source: 'Curated Guide',
          kind: s.kind,
          why: s.why,
          visitMinutes: s.visitMinutes,
          feeInr: s.feeInr,
          feeIsEstimated: false,
          isOutdoor: s.isOutdoor,
          isTrending: s.isTrending,
          openingHours: s.openingHours,
          wikiTitle: s.wikiTitle,
          sources: [
            SourceRef(
              title: s.name,
              url: s.wikiTitle != null
                  ? 'https://en.wikipedia.org/wiki/${Uri.encodeComponent(s.wikiTitle!)}'
                  : 'https://en.wikipedia.org/wiki/${Uri.encodeComponent(destination)}',
              source: 'Curated Guide',
            ),
          ],
        )..importance = s.isTrending ? 0.85 : 0.95,
    ];
  }
}
