/// Port of `TripModels.kt`. These are persisted as JSON in shared preferences
/// (the Kotlin version used Gson + `Serializable`), so each type carries an
/// explicit `toJson`/`fromJson` pair rather than relying on reflection.
class TripPlan {
  const TripPlan({
    required this.id,
    required this.destination,
    required this.title,
    required this.durationDays,
    required this.travelDates,
    required this.travelMode,
    required this.co2SavedKg,
    required this.pulsePointsEarned,
    required this.isCompleted,
    required this.hotelName,
    required this.hotelRating,
    required this.isStepFreeAccessible,
    required this.totalBudgetInr,
    required this.aqiStatus,
    required this.transitCostInr,
    required this.dailyItinerary,
    this.transitOpt1Name,
    this.transitOpt1Metrics,
    this.transitOpt2Name,
    this.transitOpt2Metrics,
    this.transitOpt3Name,
    this.transitOpt3Metrics,
    this.source = 'offline_estimate',
  });

  final String id;
  final String destination;
  final String title;
  final int durationDays;
  final String travelDates;

  /// "Electric Express Train", "MSRTC E-Bus", "Shared EV", …
  final String travelMode;
  final double co2SavedKg;
  final int pulsePointsEarned;
  final bool isCompleted;
  final String hotelName;
  final double hotelRating;
  final bool isStepFreeAccessible;
  final int totalBudgetInr;

  /// "Good (AQI 32)", "Moderate (AQI 65)", …
  final String aqiStatus;
  final int transitCostInr;
  final List<TripDaySchedule> dailyItinerary;
  final String? transitOpt1Name;
  final String? transitOpt1Metrics;
  final String? transitOpt2Name;
  final String? transitOpt2Metrics;
  final String? transitOpt3Name;
  final String? transitOpt3Metrics;

  /// `groq_ai` when genuinely generated by a live Groq call, `offline_estimate`
  /// when the Groq call was unavailable/failed and a scripted template was used
  /// instead — lets the UI avoid claiming "Verified" for content that wasn't
  /// actually produced by the AI or fetched live.
  final String source;

  bool get isAiGenerated => source == 'groq_ai';

  Map<String, dynamic> toJson() => {
    'id': id,
    'destination': destination,
    'title': title,
    'durationDays': durationDays,
    'travelDates': travelDates,
    'travelMode': travelMode,
    'co2SavedKg': co2SavedKg,
    'pulsePointsEarned': pulsePointsEarned,
    'isCompleted': isCompleted,
    'hotelName': hotelName,
    'hotelRating': hotelRating,
    'isStepFreeAccessible': isStepFreeAccessible,
    'totalBudgetInr': totalBudgetInr,
    'aqiStatus': aqiStatus,
    'transitCostInr': transitCostInr,
    'dailyItinerary': dailyItinerary.map((d) => d.toJson()).toList(),
    'transitOpt1Name': transitOpt1Name,
    'transitOpt1Metrics': transitOpt1Metrics,
    'transitOpt2Name': transitOpt2Name,
    'transitOpt2Metrics': transitOpt2Metrics,
    'transitOpt3Name': transitOpt3Name,
    'transitOpt3Metrics': transitOpt3Metrics,
    'source': source,
  };

  static TripPlan fromJson(Map<String, dynamic> json) => TripPlan(
    id: json['id'] as String? ?? '',
    destination: json['destination'] as String? ?? '',
    title: json['title'] as String? ?? '',
    durationDays: (json['durationDays'] as num?)?.toInt() ?? 1,
    travelDates: json['travelDates'] as String? ?? '',
    travelMode: json['travelMode'] as String? ?? '',
    co2SavedKg: (json['co2SavedKg'] as num?)?.toDouble() ?? 0,
    pulsePointsEarned: (json['pulsePointsEarned'] as num?)?.toInt() ?? 0,
    isCompleted: json['isCompleted'] as bool? ?? false,
    hotelName: json['hotelName'] as String? ?? '',
    hotelRating: (json['hotelRating'] as num?)?.toDouble() ?? 0,
    isStepFreeAccessible: json['isStepFreeAccessible'] as bool? ?? false,
    totalBudgetInr: (json['totalBudgetInr'] as num?)?.toInt() ?? 0,
    aqiStatus: json['aqiStatus'] as String? ?? '',
    transitCostInr: (json['transitCostInr'] as num?)?.toInt() ?? 0,
    dailyItinerary: (json['dailyItinerary'] as List<dynamic>? ?? const [])
        .map((d) => TripDaySchedule.fromJson(d as Map<String, dynamic>))
        .toList(),
    transitOpt1Name: json['transitOpt1Name'] as String?,
    transitOpt1Metrics: json['transitOpt1Metrics'] as String?,
    transitOpt2Name: json['transitOpt2Name'] as String?,
    transitOpt2Metrics: json['transitOpt2Metrics'] as String?,
    transitOpt3Name: json['transitOpt3Name'] as String?,
    transitOpt3Metrics: json['transitOpt3Metrics'] as String?,
    source: json['source'] as String? ?? 'offline_estimate',
  );
}

class TripDaySchedule {
  const TripDaySchedule({
    required this.dayNumber,
    required this.dayTitle,
    required this.activities,
  });

  final int dayNumber;
  final String dayTitle;
  final List<TripActivity> activities;

  Map<String, dynamic> toJson() => {
    'dayNumber': dayNumber,
    'dayTitle': dayTitle,
    'activities': activities.map((a) => a.toJson()).toList(),
  };

  static TripDaySchedule fromJson(Map<String, dynamic> json) => TripDaySchedule(
    dayNumber: (json['dayNumber'] as num?)?.toInt() ?? 1,
    dayTitle: json['dayTitle'] as String? ?? '',
    activities: (json['activities'] as List<dynamic>? ?? const [])
        .map((a) => TripActivity.fromJson(a as Map<String, dynamic>))
        .toList(),
  );
}

class TripActivity {
  const TripActivity({
    required this.time,
    required this.title,
    required this.description,
    required this.transportType,
    required this.isAccessible,
    required this.co2Grams,
    required this.costInr,
  });

  final String time;
  final String title;
  final String description;

  /// "Metro", "Train", "E-Bus", "Walk", "Hotel", …
  final String transportType;
  final bool isAccessible;
  final int co2Grams;
  final int costInr;

  Map<String, dynamic> toJson() => {
    'time': time,
    'title': title,
    'description': description,
    'transportType': transportType,
    'isAccessible': isAccessible,
    'co2Grams': co2Grams,
    'costInr': costInr,
  };

  static TripActivity fromJson(Map<String, dynamic> json) => TripActivity(
    time: json['time'] as String? ?? '',
    title: json['title'] as String? ?? '',
    description: json['description'] as String? ?? '',
    transportType: json['transportType'] as String? ?? '',
    isAccessible: json['isAccessible'] as bool? ?? true,
    co2Grams: (json['co2Grams'] as num?)?.toInt() ?? 0,
    costInr: (json['costInr'] as num?)?.toInt() ?? 0,
  );
}

/// A quick multiple-choice prompt attached to an assistant chat bubble.
class QuickMcqQuestion {
  const QuickMcqQuestion({
    required this.questionId,
    required this.questionText,
    required this.options,
  });

  final String questionId;
  final String questionText;
  final List<String> options;
}
